[package]
name = "simple-observable"
version = "0.2.0"
edition = "2021"
authors = ["KurlykovDanila"]
description = "Simple observable pointer for mutable and immutable data"
readme = "README.md"
license = "MIT"

keywords = ["event", "observer"]
categories = ["data-structures"]

[dependencies]
