[package]
name = "observable"
version = "0.1.0"
edition = "2021"
authors = ["KurlykovDanila"]
description = "Simple observable pointer for mutable and immutable data"
readme = "README.md"

[dependencies]
